### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by NezaLesnjak** [CebuljIza/Jaz-pa-pojdem#1]
Pozdravljeni, z delom na projektu sva končali, imava samo težavo z Binderjem, ki ne deluje dlje od začetne prijavne strani. Je potrebno mogoče še kaj spremeniti?

**Comment by majbc1999** [comment]
Živjo! Sem pregledal malo vajin projekt in imam nekaj komentarjev oz. pripomb:

1. Stran `Moji podatki` mi ne deluje oz. ne prikaže mojih podatkov. Malo sem se potem igral z vajino kodo in ugotovil, da precej bolje deluje, če namesto `JOIN`ov uporabljata `LEFT JOIN`e. Vsaj v mojem primeru to potem dobro dela in mi izpiše osebne podatke.
```python
@get('/podatki_prijavljenega')
def podatki_prijavljenega():
    uporabnik = preveriUporabnika()
    if uporabnik is None: 
        return
    uporabnisko_ime = request.get_cookie("uporabnisko_ime", secret=skrivnost)
    cur.execute("""SELECT uporabnisko_ime,ime,priimek,datum_rojstva,ime_drzave,geslo,ime_skupine,oseba.st_izleta,ime_mesta
                FROM oseba
                LEFT JOIN drzava ON oseba.drzavljanstvo=drzava.kratica
                LEFT JOIN skupina ON oseba.clanstvo=skupina.id_skupine
                LEFT JOIN obisk ON oseba.st_izleta=obisk.st_izleta
                LEFT JOIN mesto ON obisk.id_mesta=mesto.id
                WHERE uporabnisko_ime=%s;""",[uporabnisko_ime])
    return template('podatki_prijavljenega.html', oseba=cur)
```
2.  Rad bi videl, da nekje demonstrirata tudi brisanje podatkov iz baze. To lahko storita kjerkoli: lahko recimo omogočita brisanje izletov ali namestitev, ali pa skupin. Verjamem, da vama to ne bo vzelo preveč časa. Lahko samo dodata zraven tabele skupin še gumbek, s katerim izbrišemo skupino ali kaj podobnega.
3.  Pri binderju imata težavo, saj v `.html` datotekah ne uporabljata funkcije `url` za redirecte. Na primer, bolj pravilno bi bilo v datoteki `prijava.html` naslednje:
```html
% setdefault('naslov', 'Prijava')
% rebase('osnova.html')

<form action="{{url('prijava_post')}}" method="post" autocomplete="off">
    <div class="form-row">
...
```
Sicer pa se mi zdi vajin projekt dober, vse ostalo dela brez problemov. Sporočita mi, ko popravita še zgornje tri probleme, da še enkrat pregledam in odobrim vajin projekt

**Comment by jaanos** [comment]
Mimogrede, funkcijo `url` bo potrebno uporabiti tudi pri tej preusmeritvi:
https://github.com/CebuljIza/Jaz-pa-pojdem/blob/5920fe3816bd38a55722bb61a01732578c6938b0/projekt.py#L52
Kot vidim, jo pri ostalih preusmeritvah že uporabljata.

**Comment by izazupan** [comment]
Pozdravljeni, hvala za komentarje ob najinem projektu. Binder sedaj dela, funkcijo brisanja pa sva vključili pri skupinah.
S tem, vkolikor drugih opomb nimate, z delom zaključujeva. Hvala za vso pomoč.

**Comment by majbc1999** [comment]
Živjo, sem pregledal in vse dela, razen pri brisanju skupin imata problem, saj noče zbrisati skupin, v katerih so ljudje. To je zaradi reference iz tabele oseba (noče izbrisati skupin, ki so navedene v tabeli oseba). Zato morata najprej nastaviti `NULL` za članstvo vsem osebam, ki so v skupini. To storita preprosto:
```python
@post('/izbrisi_skupino')
def izbrisi_skupino_post():
    uporabnik = preveriUporabnika()
    if uporabnik is None: 
        return
    id_skupine = request.forms.id_skupine
    try:
        cur.execute("UPDATE oseba SET clanstvo = NULL WHERE clanstvo={0}".format(id_skupine))
        cur.execute("DELETE FROM skupina WHERE id_skupine={0}".format(id_skupine))
        conn.commit()
    except Exception as ex:
        conn.rollback()
        return template('izbrisi_skupino.html', id_skupine=id_skupine,
                        napaka='Zgodila se je napaka: %s' % ex, skupine=najdi_id_skupine())
    redirect(url('skupine'))
``` 
Ko popravita to, mi sporočita, da napišem Janošu, da vaju doda med opravljene projekte.

**Comment by jaanos** [comment]
Seveda pazita še na to, da ne odpirata možnosti napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/) - tako kot drugod podajta `id_skupine` v seznamu kot drugi argument metode `execute` (tj., ga ne vstavljate v niz z metodo `format` ali na kak drug način), npr.
```python
cur.execute("UPDATE oseba SET clanstvo = NULL WHERE clanstvo = %s", [id_skupine])
```

**Comment by NezaLesnjak** [comment]
Hvala za komentarje, sva uredili.

**Comment by jaanos** [comment]
V redu, sem dodal povezavo do projekta na repozitorij za zagovore. Če se še nista, se lahko z @alenFMF domenita za termin zagovora. Če bosta do takrat še kaj spreminjali, mi javita, da posodobim povezavo.

**Comment by NezaLesnjak** [comment]
Zaradi sprememb bi prosila za posodobitev povezave.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.

**Comment by izazupan** [comment]
Pozdravljeni, še zadnjič bi vas lepo prosila za posodobitev povezave. Hvala :)

**Comment by jaanos** [comment]
Velja, posodobljeno.
